version: '3.8'
services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    restart: unless-stopped
